index_title: Socialtext S3 JavaScript Testing
import_libs:
  - ../../common/javascript/jquery-1.2.6.js
  - ../../common/javascript/jquery-json-1.3.js
  - ../common/lib/Test/Visual.js
  - lib/Test/Socialtext.js
  - lib/Socialtext/Base.js
  - lib/Socialtext/Group.js
  - lib/Socialtext/User.js
  - lib/Socialtext/Workspace.js
  - lib/Socialtext/Account.js
  - lib/Socialtext/UserAccountRole.js
