index_title: Socialtext Performance Testing
import_libs:
  - ../../common/javascript/prototype-1.4.0/dist/prototype.js
  - ../../s2/javascript/pageview.js
  - ../../common/javascript/jquery-1.2.6.js
  - ../../common/javascript/Ajax-0.11/lib/Ajax.js
  - ../../common/javascript/Subclass-0.10/lib/Subclass.js
  - lib/Test/Performance.js
  - ../../s2/javascript/Debug.js
template_include_path:
  - ../common/template
  - ./template
