index_title: Socialtext Widgets JavaScript Testing
import_libs:
  - ../../s2/javascript/JSON.js
  - ../../s2/javascript/Cookie.js
  - ../../common/javascript/jquery-1.2.6.js
  - ../common/lib/Test/Visual.js
template_include_path:
  - ./template
  - ../common/template
